services:
  web:
#    build: .
    image: joaosousa00/tut-rest:v0.1
    ports:
      - "8000:5000"
    env_file:
      - web.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      app_network:

  db:
    image: oscarfonts/h2
    ports:
      - "81:81"  # Exposing port to access H2 Console
      - "1521:1521"  # Exposing port for H2 TCP server
    hostname: db
    container_name: db
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -tcp -tcpAllowOthers # H2 configuration to allow web and TCP access
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:81" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    volumes:
      - db_data:/opt/h2-data
    networks:
      app_network:

volumes:
  db_data:

networks:
  app_network: